const samples = [
  {id:'s1',title:'二手 iPhone 手機，適合日常使用',price:8500,category:'3C／手機',region:'新北市',condition:'良好',icon:'📱',photo:'https://images.unsplash.com/photo-1522591599907-d8bd97c4c948?auto=format&fit=crop&w=700&q=78',credit:'Nikolay',source:'https://unsplash.com/photos/space-gray-iphone-x-on-desk-vBnTTx0P1Jo',cover:'linear-gradient(140deg,#deeff6,#b6d7e7)',seller:'藍色小島',desc:'示範刊登：日常使用痕跡，電池健康度請以現場檢查為準。可約公共場所面交。',type:'出售'},
  {id:'s2',title:'實木邊桌，小空間也放得下',price:900,category:'家具家電',region:'台北市',condition:'近全新',icon:'🪑',photo:'https://images.unsplash.com/photo-1568842377941-63a9550044bf?auto=format&fit=crop&w=700&q=78',credit:'Josh Hemsley',source:'https://unsplash.com/photos/brown-wooden-side-table-TovSmcuAfRM',cover:'linear-gradient(140deg,#f8e9d9,#e8c7aa)',seller:'木日子',desc:'示範刊登：搬家整理，桌面平整。尺寸與運送方式請在正式服務開放後確認。',type:'出售'},
  {id:'s3',title:'底片相機交換提案',price:0,category:'收藏品',region:'新北市',condition:'良好',icon:'📷',photo:'https://images.unsplash.com/photo-1659215714329-4800865c98e4?auto=format&fit=crop&w=700&q=78',credit:'Emre',source:'https://unsplash.com/photos/a-camera-on-a-table-XvGC9B1nVLE',cover:'linear-gradient(140deg,#d9e4ec,#a7beca)',seller:'光影散步',desc:'示範刊登：希望交換可正常使用的相機，歡迎提出物品與狀況。',type:'交換'},
  {id:'s4',title:'露營折疊椅，輕巧好收納',price:1200,category:'運動戶外',region:'桃園市',condition:'良好',icon:'🏕️',photo:'https://images.unsplash.com/photo-1758696719227-5ebafad63088?auto=format&fit=crop&w=700&q=78',credit:'ap hakeisolai',source:'https://unsplash.com/photos/a-black-folding-chair-sits-outdoors-near-plants-bOknNPmMs10',cover:'linear-gradient(140deg,#e4f0d9,#b8d1ae)',seller:'週末出走',desc:'示範刊登：使用過數次，功能正常。',type:'出售'},
  {id:'s5',title:'童書一組，分享給下一位小讀者',price:0,category:'書籍文具',region:'新北市',condition:'良好',icon:'📚',photo:'https://images.unsplash.com/photo-1723831101652-c03827729b5a?auto=format&fit=crop&w=700&q=78',credit:'Alicia Christin Gerald',source:'https://unsplash.com/photos/a-pile-of-childrens-books-sitting-on-top-of-each-other-SmCkmNjqrjI',cover:'linear-gradient(140deg,#f6e6dd,#e7b8a6)',seller:'一起讀書',desc:'示範刊登：多本童書，書況依現場檢查為準。',type:'贈與'},
  {id:'s6',title:'充電式電鑽，家用維修好幫手',price:1800,category:'工具',region:'台北市',condition:'良好',icon:'🧰',photo:'https://images.unsplash.com/photo-1622044939413-0b829c342434?auto=format&fit=crop&w=700&q=78',credit:'Jonathan Cooper',source:'https://unsplash.com/photos/green-and-black-cordless-hand-drill-7sZwThSntdw',cover:'linear-gradient(140deg,#f6ecd6,#dec48b)',seller:'修修補補',desc:'示範刊登：電池與功能請在正式交易時確認。',type:'出售'},
  {id:'s7',title:'外套整理出清，日常穿搭好搭配',price:450,category:'服飾配件',region:'新北市',condition:'良好',icon:'🧥',photo:'https://images.unsplash.com/photo-1722859031306-4c81e8d83957?auto=format&fit=crop&w=700&q=78',credit:'Lisa Anna',source:'https://unsplash.com/photos/a-coat-rack-with-coats-hanging-on-it-_Ssh8Z8ENQM',cover:'linear-gradient(140deg,#f0e5ec,#d7bccb)',seller:'衣櫃探險',desc:'示範刊登：整理衣櫃釋出，尺寸請參考實際量測。',type:'出售'},
  {id:'s8',title:'彩色積木散件，讓玩具重新發光',price:600,category:'玩具母嬰',region:'台北市',condition:'良好',icon:'🧸',photo:'https://images.unsplash.com/photo-1623990670247-b2258ecf2b2a?auto=format&fit=crop&w=700&q=78',credit:'Alan Rodriguez',source:'https://unsplash.com/photos/assorted-plastic-toy-blocks-on-white-table-lt3sq8uPWs8',cover:'linear-gradient(140deg,#e8e6f4,#c6c0df)',seller:'小星球',desc:'示範刊登：二手玩具，零件請依實物核對。',type:'出售'}
];
const sampleWants=[
  {title:'想找一台適合學生的二手筆電',budget:'預算 NT$ 8,000–12,000',region:'新北市',note:'文書與線上課程使用，希望電池正常。'},
  {title:'徵求可用的嬰兒推車',budget:'預算 NT$ 2,500 內',region:'台北市',note:'希望可折疊，能在捷運站附近面交。'},
  {title:'尋找居家用電鑽或工具箱',budget:'可交換或購買',region:'新北市',note:'家中簡單修繕，有閒置工具歡迎分享。'}
];
const communities=[
  {name:'蘆洲・三重好物交流',desc:'附近的閒置好物、求物與贈與',icon:'🏘️',cover:'linear-gradient(135deg,#d6f2ea,#b1dccf)',topic:'地區社群'},
  {name:'台北二手 3C 研究所',desc:'手機、筆電與周邊的交流空間',icon:'💻',cover:'linear-gradient(135deg,#deecfa,#b9d0ed)',topic:'興趣社群'},
  {name:'親子物品接力站',desc:'讓童書、玩具與用品延續價值',icon:'🧸',cover:'linear-gradient(135deg,#fff0df,#f2d2ac)',topic:'興趣社群'}
];
const categories=['全部','3C／手機','家具家電','服飾配件','運動戶外','書籍文具','玩具母嬰','工具','收藏品'];
const app=document.getElementById('app'), modal=document.getElementById('modal'), modalContent=document.getElementById('modalContent');
const state={query:'',category:'全部',region:'全部地區'};
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const save=(key,val)=>localStorage.setItem(key,JSON.stringify(val));
const escapeHTML=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>n===0?'免費／交換':`NT$ ${Number(n).toLocaleString('zh-TW')}`;
const listings=()=>[...read('bg-listings',[]),...samples];
const favorites=()=>read('bg-favorites',[]);
function toast(message){const el=document.getElementById('toast');el.textContent=message;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),3000)}
function openModal(html){modalContent.innerHTML=html;modal.showModal()}
function closeModal(){modal.close()}
document.getElementById('closeModal').onclick=closeModal;
modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});
function photoMarkup(item,large=false){return item.photo?`<img src="${escapeHTML(large?item.photo.replace('w=700','w=1400'):item.photo)}" alt="${escapeHTML(item.category)}展示示意照片" loading="${large?'eager':'lazy'}" referrerpolicy="no-referrer">`:`<span class="emoji" aria-hidden="true">${item.icon}</span>`}
function card(item){const liked=favorites().includes(item.id);return `<article class="card"><a href="#/listing/${encodeURIComponent(item.id)}" aria-label="查看${escapeHTML(item.title)}"><div class="card-photo" style="--cover:${item.cover}">${photoMarkup(item)}<span class="tag">${escapeHTML(item.type)}</span>${item.photo?'<span class="photo-hint">照片示意</span>':''}</div></a><div class="card-body"><h3><a href="#/listing/${encodeURIComponent(item.id)}">${escapeHTML(item.title)}</a></h3><div class="price">${money(item.price)}${item.price?`<small>${escapeHTML(item.condition)}</small>`:''}</div><div class="meta"><span>⌖ ${escapeHTML(item.region)}</span><span>${escapeHTML(item.seller)}</span></div></div><button class="save ${liked?'on':''}" data-save="${escapeHTML(item.id)}" aria-label="${liked?'取消收藏':'收藏'}${escapeHTML(item.title)}">${liked?'♥':'♡'}</button></article>`}
function wantCard(w,i){return `<article class="want-card"><span class="pill">我想找</span><h3>${escapeHTML(w.title)}</h3><p>${escapeHTML(w.note)}</p><footer><span>⌖ ${escapeHTML(w.region)} · ${escapeHTML(w.budget)}</span><button data-want="${i}">看看需求</button></footer></article>`}
function communityCard(c,i){return `<button class="community-card" data-community="${i}"><span class="community-icon" style="--cover:${c.cover}">${c.icon}</span><span><h3>${escapeHTML(c.name)}</h3><p>${escapeHTML(c.desc)}</p><small>${c.topic} · 查看介紹</small></span></button>`}
function section(title,sub,link,content){return `<div class="section-title"><div><h2>${title}</h2><p>${sub}</p></div>${link?`<a class="section-link" href="${link[1]}">${link[0]}　›</a>`:''}</div>${content}`}
function filters(){return `<div class="search-panel"><form id="searchForm" class="search-line"><label class="search-wrap"><span>⌕</span><input id="searchInput" type="search" autocomplete="off" placeholder="搜尋商品、品牌或關鍵字" value="${escapeHTML(state.query)}" aria-label="搜尋商品"></label><select id="regionSelect" aria-label="選擇地區">${['全部地區','新北市','台北市','桃園市'].map(r=>`<option ${state.region===r?'selected':''}>${r}</option>`).join('')}</select><button>搜尋</button></form><div class="chips" aria-label="商品分類">${categories.map(c=>`<button class="chip ${state.category===c?'active':''}" data-category="${escapeHTML(c)}">${escapeHTML(c)}</button>`).join('')}</div></div>`}
function filtered(){return listings().filter(i=>(state.category==='全部'||i.category===state.category)&&(state.region==='全部地區'||i.region===state.region)&&(!state.query||`${i.title} ${i.desc} ${i.category}`.toLowerCase().includes(state.query.toLowerCase())))}
function explore(){const items=filtered();app.innerHTML=`<div class="hero"><section class="hero-main"><div><span class="eyebrow">二手好物 · 在地相遇</span><h1>讓閒置成為<br>下一個人的剛好</h1><p>逛二手、找需要的物品，也能在附近社群交流。免費刊登，從一件好物開始。</p><button class="hero-cta" data-publish>免費刊登好物</button></div></section><div class="hero-side"><button class="side-card one" data-route="wants"><span><strong>你在找什麼？</strong><small>發布求物需求，等好物來敲門</small></span><span class="symbol">◎</span></button><button class="side-card two" data-route="communities"><span><strong>逛逛附近社群</strong><small>讓交流從熟悉的地方開始</small></span><span class="symbol">◫</span></button></div></div>${filters()}${section('正在被發現的好物','商品與照片為展示示意；你刊登的內容只顯示於此裝置',null,items.length?`<div class="grid">${items.map(card).join('')}</div>`:`<div class="empty"><span class="big">⌕</span><strong>目前沒有符合條件的物品</strong><p>換個關鍵字或地區試試看。</p><button class="secondary" id="clearFilters">清除篩選</button></div>`)}${section('大家正在找','有需求，也有讓閒置被看見的機會',['查看所有需求','#/wants'],`<div class="want-grid">${sampleWants.map(wantCard).join('')}</div>`)}${section('在地與興趣社群','從共同話題開始交流',['探索社群','#/communities'],`<div class="community-grid">${communities.map(communityCard).join('')}</div>`)}`}
function wants(){app.innerHTML=`<div class="page-hero"><div><h1>我想找</h1><p>找不到想要的？把需求寫下來，讓有閒置物品的人看見。</p></div><span class="symbol">◎</span></div><div class="page-head"><div><h1>最新求物需求</h1><p>示例需求供你了解媒合形式；目前尚未啟用會員對話。</p></div><button class="primary" data-publish-type="求物">＋ 發布需求</button></div><div class="want-grid">${[...read('bg-wants',[]),...sampleWants].map(wantCard).join('')}</div><div class="notice">需求對話正式開放後，發起對接前會清楚顯示點數費用；同一需求的既有對話不會重複扣點。</div>`}
function communityPage(){app.innerHTML=`<div class="page-hero"><div><h1>在地社群</h1><p>從地區與興趣出發，探索值得分享的好物和話題。</p></div><span class="symbol">◫</span></div><div class="page-head"><div><h1>探索社群</h1><p>社群名稱與內容為展示範例；追蹤與貼文將在會員服務上線後開放。</p></div></div><div class="community-grid">${communities.map(communityCard).join('')}</div><div class="notice">社群公開內容可免費瀏覽。私人聯絡將導回站內對話，平台會阻擋直接聯絡資料。</div>`}
function mine(){const items=listings().filter(i=>favorites().includes(i.id));const own=read('bg-listings',[]);app.innerHTML=`<div class="page-head"><div><h1>我的收藏</h1><p>收藏與示範刊登會保存在你目前的瀏覽器中。</p></div></div>${items.length?`<div class="grid">${items.map(card).join('')}</div>`:`<div class="empty"><span class="big">♡</span><strong>還沒有收藏的好物</strong><p>逛逛商品，點選愛心把喜歡的物品收在這裡。</p><a class="primary" href="#/explore">去逛好物</a></div>`}<div class="section-title"><div><h2>我的示範刊登</h2><p>資料只存在此裝置，不會公開給其他人</p></div><button class="secondary" data-publish>＋ 新增刊登</button></div>${own.length?`<div class="grid">${own.map(card).join('')}</div>`:`<div class="empty"><strong>目前沒有刊登</strong><p>建立一則示範刊登，先試試表單流程。</p></div>`}`}
function detail(id){const item=listings().find(i=>i.id===id);if(!item){app.innerHTML='<div class="empty"><strong>找不到這則刊登</strong><p>它可能已從此裝置移除。</p><a href="#/explore" class="primary">返回逛好物</a></div>';return}app.innerHTML=`<p style="font-size:13px;color:#8aa0af;margin:1px 0 18px"><a href="#/explore">逛好物</a>　/　${escapeHTML(item.category)}</p><div class="detail"><div class="detail-photo" style="--cover:${item.cover}" aria-label="${escapeHTML(item.category)}示意照片">${photoMarkup(item,true)}</div><div class="detail-copy"><span class="chip active">${escapeHTML(item.type)}</span><h1>${escapeHTML(item.title)}</h1><div class="detail-price">${money(item.price)}</div><p class="detail-desc">${escapeHTML(item.desc)}</p><div class="detail-list"><span>物品狀況</span><strong>${escapeHTML(item.condition)}</strong><span>所在地區</span><strong>${escapeHTML(item.region)}</strong><span>刊登暱稱</span><strong>${escapeHTML(item.seller)}</strong><span>交易方式</span><strong>正式服務上線後由雙方站內確認</strong></div><div class="detail-actions"><button class="primary" data-contact="${escapeHTML(item.id)}">發起站內對話</button><button class="secondary" data-save="${escapeHTML(item.id)}">${favorites().includes(item.id)?'♥ 已收藏':'♡ 收藏'}</button></div><div class="notice">展示資料與照片僅供介面示意，不代表實際出售。正式啟用前不會扣點、收款或傳送訊息。</div>${item.source?`<p class="photo-credit">示意照片：<a href="${escapeHTML(item.source)}" target="_blank" rel="noopener noreferrer">${escapeHTML(item.credit)} / Unsplash</a></p>`:''}</div></div>`}
function render(){let route=location.hash.slice(2).split('/');let page=route[0]||'explore';if(page==='wants')wants();else if(page==='communities')communityPage();else if(page==='mine')mine();else if(page==='listing')detail(decodeURIComponent(route[1]||''));else{page='explore';explore()}document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===page));window.scrollTo({top:0,behavior:'instant'})}
function publish(type='出售'){openModal(`<h2 class="modal-title">免費刊登</h2><p class="modal-intro">先建立一則示範刊登，確認資訊呈現方式。資料僅儲存在此裝置，其他會員看不到。</p><form id="publishForm"><label class="field">刊登類型<select name="type" required>${['出售','求物','贈與','交換'].map(t=>`<option ${type===t?'selected':''}>${t}</option>`).join('')}</select></label><label class="field">標題<input name="title" maxlength="60" required placeholder="例如：良好二手書桌一張"></label><div class="form-row"><label class="field">分類<select name="category">${categories.slice(1).map(c=>`<option>${c}</option>`).join('')}</select></label><label class="field">所在地區<select name="region"><option>新北市</option><option>台北市</option><option>桃園市</option><option>其他地區</option></select></label></div><div class="form-row"><label class="field">價格／預算（NT$）<input name="price" type="number" min="0" max="100000000" value="0" required></label><label class="field">物況<select name="condition"><option>良好</option><option>近全新</option><option>有使用痕跡</option><option>待確認</option></select></label></div><label class="field">內容說明<textarea name="desc" maxlength="500" required placeholder="描述物品狀況、需求條件與可接受的交付方式"></textarea></label><label class="field">顯示暱稱<input name="seller" maxlength="20" required placeholder="不要填真實姓名或聯絡方式"></label><div class="form-actions"><button type="button" class="secondary" id="cancelPublish">取消</button><button class="primary">儲存示範刊登</button></div><p class="fineprint">請勿輸入姓名、電話、Email、LINE ID、社群帳號或外部連結。照片上傳、審核及公開刊登尚未啟用。</p></form>`)}
const contactPattern=/(?:\b(?:09\d{2}[\s.-]?\d{3}[\s.-]?\d{3}|0\d{1,2}[\s.-]?\d{3,4}[\s.-]?\d{4})\b|[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}|(?:https?:\/\/|www\.)\S+|(?:line\s*(?:id|[:：])|instagram|facebook|ig\s*[:：]|加賴|加line)\s*\S*)/i;
function submitPublish(form){const data=Object.fromEntries(new FormData(form));if(contactPattern.test(`${data.title} ${data.desc} ${data.seller}`)){toast('請移除電話、Email、LINE 或外部連結後再試');return}const type=data.type;if(type==='求物'){let wants=read('bg-wants',[]);wants.unshift({title:data.title,note:data.desc,budget:data.price>0?`預算 NT$ ${Number(data.price).toLocaleString('zh-TW')}`:'預算可談',region:data.region});save('bg-wants',wants);closeModal();location.hash='#/wants';render();toast('示範需求已儲存在此裝置');return}const icons={'3C／手機':'📱','家具家電':'🪑','服飾配件':'🧥','運動戶外':'🏕️','書籍文具':'📚','玩具母嬰':'🧸','工具':'🧰','收藏品':'📷'};const item={id:`local-${Date.now()}`,title:data.title,desc:data.desc,price:Number(data.price),category:data.category,region:data.region,condition:data.condition,seller:data.seller,type,icon:icons[data.category],cover:'linear-gradient(140deg,#e2f2f1,#bddbdf)'};let own=read('bg-listings',[]);own.unshift(item);save('bg-listings',own);closeModal();location.hash=`#/listing/${item.id}`;render();toast('示範刊登已儲存在此裝置')}
function info(which){const content={rules:['平台規則','免費瀏覽與刊登。禁止刊登受限制物品、詐騙內容，以及在刊登、圖片或對話中交換電話、Email、LINE 等站外聯絡方式。正式服務將提供檢舉、審核、申訴與交易爭議處理。'],privacy:['隱私與化名','公開頁僅顯示暱稱與必要的刊登資料。正式服務需要付款或物流資料時，會另行告知蒐集用途、權限與合作方；交易另一方不會看到不必要的個資。展示版資料只留在此瀏覽器。'],fees:['點數與服務費','正式服務預計在發起每件商品或需求的站內對話前清楚顯示點數費用；同一對話不重複扣點。二手買賣完成後，規劃依雙方最終成交價收取 10% 服務費，預設由賣家負擔並於付款前揭露。點數費率、退款及效期仍待公告；目前沒有收款或扣點。']}[which];openModal(`<h2 class="modal-title">${content[0]}</h2><p class="modal-intro" style="margin-top:18px;color:#4a6578">${content[1]}</p><button class="primary" id="gotIt">了解</button>`)}
document.addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return;if(t.matches('[data-save]')){e.preventDefault();let set=new Set(favorites());set.has(t.dataset.save)?set.delete(t.dataset.save):set.add(t.dataset.save);save('bg-favorites',[...set]);render();toast(set.has(t.dataset.save)?'已加入收藏':'已取消收藏')}else if(t.matches('[data-category]')){state.category=t.dataset.category;render()}else if(t.matches('[data-publish],[data-publish-type]'))publish(t.dataset.publishType||'出售');else if(t.matches('[data-route]'))location.hash=`#/${t.dataset.route}`;else if(t.matches('[data-contact]'))openModal('<h2 class="modal-title">站內對話尚未開放</h2><p class="modal-intro">目前是產品展示版，沒有真實會員、點數扣款或訊息傳送。正式開放後，會在發起對話前顯示點數費用並取得你的確認；同一對話不重複扣點。</p><button class="primary" id="gotIt">了解</button>');else if(t.matches('[data-community]')){const c=communities[Number(t.dataset.community)];openModal(`<h2 class="modal-title">${escapeHTML(c.icon)} ${escapeHTML(c.name)}</h2><p class="modal-intro">${escapeHTML(c.desc)}</p><div class="notice">這是社群版型示例。追蹤、貼文及通知會在會員服務建置後開放。</div><div class="form-actions"><button class="primary" id="gotIt">了解</button></div>`)}else if(t.matches('[data-want]')){const w=[...read('bg-wants',[]),...sampleWants][Number(t.dataset.want)];if(w)openModal(`<h2 class="modal-title">${escapeHTML(w.title)}</h2><p class="modal-intro">${escapeHTML(w.note)}</p><div class="detail-list"><span>地區</span><strong>${escapeHTML(w.region)}</strong><span>預算</span><strong>${escapeHTML(w.budget)}</strong></div><div class="notice">站內對話仍在建置，示例需求無法聯絡。</div><div class="form-actions"><button class="primary" id="gotIt">了解</button></div>`)}else if(t.id==='clearFilters'){state.query='';state.category='全部';state.region='全部地區';render()}else if(t.dataset.info)info(t.dataset.info);else if(t.id==='cancelPublish'||t.id==='gotIt')closeModal()});
document.addEventListener('submit',e=>{if(e.target.id==='searchForm'){e.preventDefault();state.query=document.getElementById('searchInput').value.trim();state.region=document.getElementById('regionSelect').value;render()}else if(e.target.id==='publishForm'){e.preventDefault();submitPublish(e.target)}});
document.getElementById('topPublish').onclick=()=>publish();document.getElementById('bottomPublish').onclick=()=>publish();document.getElementById('topSearch').onclick=()=>{location.hash='#/explore';setTimeout(()=>document.getElementById('searchInput')?.focus(),30)};
window.addEventListener('hashchange',render);render();
